# Generated by Django 4.1.7 on 2023-06-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_alter_category_options_item"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ("name",), "verbose_name_plural": "items"},
        ),
        migrations.RenameField(
            model_name="item",
            old_name="description",
            new_name="links",
        ),
        migrations.RemoveField(
            model_name="item",
            name="Created_by",
        ),
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.RemoveField(
            model_name="item",
            name="created_at",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
